### ISSUE TITLE
Ability to add an image overlay to the imposing satellite dish

### ISSUE THREAD

**Issue by robin13** [radoondas/radoondas.io#1]
It would be neat to be able to add an overlay image to the imposing satellite dish:

![tatry](https://user-images.githubusercontent.com/174291/122888079-cd8f7d00-d341-11eb-9943-52516747f9a8.jpeg)

The image could be:
- A site sponsor
- Fan submitted (rotate through)
- Owner selected (e.g. face of a friend to celebrate their birthday)
- ...
The options are limitless! :)

**Comment by radoondas** [comment]
I decided to replace the satelite dish with the logo of the National park. Hope this is good enough. WDYT?
![tatry-dish](https://user-images.githubusercontent.com/8320348/123252667-d53f5500-d4ec-11eb-98ee-9d614d4ffb3a.jpeg)

**Comment by robin13** [comment]
Seems like a worthy cause! :)

**Comment by radoondas** [comment]
The change is live, so I am closing the issue.
